package com.risecode.riseflow.commercial.api;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.risecode.riseflow.commercial.domain.Invoice;
import com.risecode.riseflow.commercial.domain.InvoiceItem;
import com.risecode.riseflow.commercial.domain.InvoiceStatus;
import com.risecode.riseflow.commercial.events.InvoicePaidEvent;
import com.risecode.riseflow.commercial.payment.PaymentGateway;
import com.risecode.riseflow.commercial.payment.PaymentResult;
import com.risecode.riseflow.commercial.persistence.InvoiceItemRepository;
import com.risecode.riseflow.commercial.persistence.InvoiceRepository;
import com.risecode.riseflow.core.exception.BusinessException;
import com.risecode.riseflow.core.exception.EntityNotFoundException;
import com.risecode.riseflow.core.exception.TenantMismatchException;
import com.risecode.riseflow.core.tenant.TenantContextHolder;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.context.ApplicationEventPublisher;

@ExtendWith(MockitoExtension.class)
class InvoiceServiceTest {

    @Mock InvoiceRepository invoiceRepository;
    @Mock InvoiceItemRepository invoiceItemRepository;
    @Mock PaymentGateway paymentGateway;
    @Mock ApplicationEventPublisher eventPublisher;

    @InjectMocks InvoiceService invoiceService;

    @AfterEach
    void tearDown() {
        TenantContextHolder.clear();
    }

    @Test
    void shouldCreateInvoice_withAutoGeneratedNumber() {
        UUID tenantId = UUID.randomUUID();
        UUID accountId = UUID.randomUUID();
        TenantContextHolder.setTenantId(tenantId);

        when(invoiceRepository.countByTenantId(tenantId)).thenReturn(0L);
        when(invoiceRepository.save(any(Invoice.class))).thenAnswer(inv -> {
            Invoice i = inv.getArgument(0);
            i.setId(UUID.randomUUID());
            return i;
        });
        when(invoiceItemRepository.save(any(InvoiceItem.class))).thenAnswer(inv -> {
            InvoiceItem item = inv.getArgument(0);
            item.setId(UUID.randomUUID());
            return item;
        });

        InvoiceRequest request = new InvoiceRequest(
                accountId, null, null, null,
                LocalDate.now().plusDays(30),
                List.of(new InvoiceItemRequest("Service", BigDecimal.ONE, BigDecimal.valueOf(200), 1)));

        InvoiceResponse response = invoiceService.createInvoice(request);

        assertThat(response.invoiceNumber()).startsWith("INV-");
        assertThat(response.status()).isEqualTo(InvoiceStatus.PENDING);
        assertThat(response.totalAmount()).isEqualByComparingTo(BigDecimal.valueOf(200));
    }

    @Test
    void shouldCreateInvoice_withProvidedNumber() {
        UUID tenantId = UUID.randomUUID();
        TenantContextHolder.setTenantId(tenantId);

        when(invoiceRepository.save(any(Invoice.class))).thenAnswer(inv -> {
            Invoice i = inv.getArgument(0);
            i.setId(UUID.randomUUID());
            return i;
        });
        when(invoiceItemRepository.save(any(InvoiceItem.class))).thenAnswer(inv -> {
            InvoiceItem item = inv.getArgument(0);
            item.setId(UUID.randomUUID());
            return item;
        });

        InvoiceRequest request = new InvoiceRequest(
                UUID.randomUUID(), null, null, "CUSTOM-001",
                LocalDate.now().plusDays(30),
                List.of(new InvoiceItemRequest("Item", BigDecimal.ONE, BigDecimal.TEN, 1)));

        InvoiceResponse response = invoiceService.createInvoice(request);

        assertThat(response.invoiceNumber()).isEqualTo("CUSTOM-001");
    }

    @Test
    void shouldMarkInvoiceAsPaid_andPublishEvent_whenFullyPaid() {
        UUID tenantId = UUID.randomUUID();
        UUID invoiceId = UUID.randomUUID();
        TenantContextHolder.setTenantId(tenantId);

        Invoice invoice = invoice(invoiceId, tenantId, InvoiceStatus.PENDING, BigDecimal.valueOf(500));
        when(invoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));
        when(invoiceRepository.save(any(Invoice.class))).thenAnswer(inv -> inv.getArgument(0));
        when(invoiceItemRepository.findAllByInvoiceIdOrderByOrderNo(invoiceId)).thenReturn(List.of());

        InvoiceResponse response = invoiceService.markAsPaid(invoiceId,
                new MarkPaidRequest("BANK_TRANSFER", BigDecimal.valueOf(500)));

        assertThat(response.status()).isEqualTo(InvoiceStatus.PAID);
        ArgumentCaptor<InvoicePaidEvent> captor = ArgumentCaptor.forClass(InvoicePaidEvent.class);
        verify(eventPublisher).publishEvent(captor.capture());
        assertThat(captor.getValue().invoiceId()).isEqualTo(invoiceId);
    }

    @Test
    void shouldMarkInvoiceAsPaid_withoutPublishingEvent_whenPartiallyPaid() {
        UUID tenantId = UUID.randomUUID();
        UUID invoiceId = UUID.randomUUID();
        TenantContextHolder.setTenantId(tenantId);

        Invoice invoice = invoice(invoiceId, tenantId, InvoiceStatus.PENDING, BigDecimal.valueOf(500));
        when(invoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));
        when(invoiceRepository.save(any(Invoice.class))).thenAnswer(inv -> inv.getArgument(0));
        when(invoiceItemRepository.findAllByInvoiceIdOrderByOrderNo(invoiceId)).thenReturn(List.of());

        InvoiceResponse response = invoiceService.markAsPaid(invoiceId,
                new MarkPaidRequest("CASH", BigDecimal.valueOf(300)));

        assertThat(response.status()).isEqualTo(InvoiceStatus.PENDING);
        org.mockito.Mockito.verifyNoInteractions(eventPublisher);
    }

    @Test
    void shouldMarkOverdueInvoice_asPaid() {
        UUID tenantId = UUID.randomUUID();
        UUID invoiceId = UUID.randomUUID();
        TenantContextHolder.setTenantId(tenantId);

        Invoice invoice = invoice(invoiceId, tenantId, InvoiceStatus.OVERDUE, BigDecimal.valueOf(100));
        when(invoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));
        when(invoiceRepository.save(any(Invoice.class))).thenAnswer(inv -> inv.getArgument(0));
        when(invoiceItemRepository.findAllByInvoiceIdOrderByOrderNo(invoiceId)).thenReturn(List.of());

        InvoiceResponse response = invoiceService.markAsPaid(invoiceId,
                new MarkPaidRequest("CARD", BigDecimal.valueOf(100)));

        assertThat(response.status()).isEqualTo(InvoiceStatus.PAID);
    }

    @Test
    void shouldRejectMarkAsPaid_whenInvoiceIsCancelled() {
        UUID tenantId = UUID.randomUUID();
        UUID invoiceId = UUID.randomUUID();
        TenantContextHolder.setTenantId(tenantId);

        Invoice invoice = invoice(invoiceId, tenantId, InvoiceStatus.CANCELLED, BigDecimal.valueOf(100));
        when(invoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));

        assertThatThrownBy(() -> invoiceService.markAsPaid(invoiceId,
                new MarkPaidRequest("CASH", BigDecimal.valueOf(100))))
                .isInstanceOf(BusinessException.class)
                .hasMessageContaining("CANCELLED");
    }

    @Test
    void shouldCancelInvoice_whenPending() {
        UUID tenantId = UUID.randomUUID();
        UUID invoiceId = UUID.randomUUID();
        TenantContextHolder.setTenantId(tenantId);

        Invoice invoice = invoice(invoiceId, tenantId, InvoiceStatus.PENDING, BigDecimal.TEN);
        when(invoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));
        when(invoiceRepository.save(any(Invoice.class))).thenAnswer(inv -> inv.getArgument(0));
        when(invoiceItemRepository.findAllByInvoiceIdOrderByOrderNo(invoiceId)).thenReturn(List.of());

        InvoiceResponse response = invoiceService.cancelInvoice(invoiceId);

        assertThat(response.status()).isEqualTo(InvoiceStatus.CANCELLED);
    }

    @Test
    void shouldRejectCancel_whenNotPending() {
        UUID tenantId = UUID.randomUUID();
        UUID invoiceId = UUID.randomUUID();
        TenantContextHolder.setTenantId(tenantId);

        Invoice invoice = invoice(invoiceId, tenantId, InvoiceStatus.PAID, BigDecimal.TEN);
        when(invoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));

        assertThatThrownBy(() -> invoiceService.cancelInvoice(invoiceId))
                .isInstanceOf(BusinessException.class)
                .hasMessageContaining("PENDING");
    }

    @Test
    void shouldCreatePayment_viaGateway() {
        UUID tenantId = UUID.randomUUID();
        UUID invoiceId = UUID.randomUUID();
        TenantContextHolder.setTenantId(tenantId);

        Invoice invoice = invoice(invoiceId, tenantId, InvoiceStatus.PENDING, BigDecimal.valueOf(250));
        invoice.setInvoiceNumber("INV-001");
        when(invoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));
        when(paymentGateway.createInvoice(any(), any(), any(), any()))
                .thenReturn(new PaymentResult("inv_abc", "pi_abc", "secret_abc", "open"));
        when(invoiceRepository.save(any(Invoice.class))).thenAnswer(inv -> inv.getArgument(0));

        CreatePaymentResponse response = invoiceService.createPayment(invoiceId);

        assertThat(response.gatewayInvoiceId()).isEqualTo("inv_abc");
        assertThat(response.paymentIntentId()).isEqualTo("pi_abc");
    }

    @Test
    void shouldThrowTenantMismatch_whenInvoiceBelongsToDifferentTenant() {
        UUID tenantId = UUID.randomUUID();
        UUID otherTenantId = UUID.randomUUID();
        UUID invoiceId = UUID.randomUUID();
        TenantContextHolder.setTenantId(tenantId);

        Invoice invoice = invoice(invoiceId, otherTenantId, InvoiceStatus.PENDING, BigDecimal.TEN);
        when(invoiceRepository.findById(invoiceId)).thenReturn(Optional.of(invoice));

        assertThatThrownBy(() -> invoiceService.getInvoice(invoiceId))
                .isInstanceOf(TenantMismatchException.class);
    }

    @Test
    void shouldThrowEntityNotFound_whenInvoiceDoesNotExist() {
        TenantContextHolder.setTenantId(UUID.randomUUID());
        UUID invoiceId = UUID.randomUUID();
        when(invoiceRepository.findById(invoiceId)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> invoiceService.getInvoice(invoiceId))
                .isInstanceOf(EntityNotFoundException.class);
    }

    private Invoice invoice(UUID id, UUID tenantId, InvoiceStatus status, BigDecimal total) {
        Invoice i = new Invoice();
        i.setId(id);
        i.setTenantId(tenantId);
        i.setAccountId(UUID.randomUUID());
        i.setInvoiceNumber("INV-2026-00001");
        i.setStatus(status);
        i.setDueDate(LocalDate.now().plusDays(30));
        i.setTotalAmount(total);
        i.setPaidAmount(BigDecimal.ZERO);
        return i;
    }
}
